steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'apps/backend/backend-api/Dockerfile',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/amazons-backend:latest',
      '.'
    ]
    env: ['DOCKER_BUILDKIT=1']
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REGISTRY_NAME}/amazons-backend:latest'

substitutions:
  _REGION: europe-west1
  _REGISTRY_NAME: amazons-repo
